### ISSUE TITLE
[Setup] Add description of how to use packages

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Docs#7]

**Comment by philliphoff** [comment]
@avanderhoorn, @nikmd23: Do we need more than what's at: https://github.com/Glimpse/Glimpse.Client.Distribution/releases/tag/v2.0.0-m005

**Comment by nikmd23** [comment]
That was all I intended. 

LGTM

**Comment by philliphoff** [comment]
Great, then I'll close this issue.
